function [fitresult, gof] = LSCAN_linescanMeanFit(x1, y1)
%CREATEFIT(X1,Y1)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : x1
%      Y Output: y1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Sep-2013 12:07:58


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( x1, y1 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( ft );
opts.SmoothingParam = 0.5218219487630378;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 2' );
% h = plot( fitresult, xData, yData );
% legend( h, 'y1 vs. x1', 'untitled fit 2', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'x1' );
% ylabel( 'y1' );
% grid on


